config/routes.rb
Rails.application.routes.draw do

  root "welcome#index"

  resources :lists do
    resources :items, :welcome
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :list
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def new
    @item = Item.new
    @list = List.find(params["list_id"])
  end

  def create
    @item = Item.new(item_params)
    @item.list_id = params["list_id"]

    if @item.save
      redirect_to list_path(id: @item.list_id)
    else
      render :new
    end
  end

  def edit
    @list = List.find(params["list_id"])
    @item = Item.find(params["id"])
  end

  def update
    @item = Item.find(params["id"])
    @list = List.find(params["list_id"])

    if @item.update(item_params)
      redirect_to list_path(@item.list_id), notice: "#{@item.task} was updated"

    else
      render :edit
    end
  end

  def destroy
    @item = Item.find(params["id"])
    @item.destroy

    redirect_to list_path(@item.list_id), notice: "#{@item.task} was successfully removed from the list"
  end


  private def item_params
    params.require("item").permit( :task )
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  def index
    @lists = List.all
  end

  # GET /lists/1
  def show
    @items = @list.items
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to @list, notice: 'List was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /lists/1
  def update
    if @list.update(list_params)
      redirect_to @list, notice: 'List was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /lists/1
  def destroy
    @list.destroy
    redirect_to lists_url, notice: 'List was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def list_params
      params.require(:list).permit(:name, :added_on, :to_be_completed_on)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    render :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= form_for [@list, @item] do |f| %>

  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :task %>
  <%= f.text_field :task %>
  <%= f.submit "Update List" %>

<% end %>

app/views/items/_item.html.erb
<tr>
  <td><%= item.task %>:</td>
  <td>
    | <%= link_to "edit item", edit_list_item_path(id: item.id, list_id: @list.id) %> |
    <%= link_to "delete", list_item_path(id: item.id, list_id: @list.id), method: :delete %>
  </td>
</tr>

app/views/items/edit.html.erb
<%= render "form" %>

app/views/items/new.html.erb
<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToDoList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :added_on %><br>
    <%= f.date_select :added_on %>
  </div>
  <div class="field">
    <%= f.label :to_be_completed_on %><br>
    <%= f.date_select :to_be_completed_on %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Current To-Do-Lists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Added on</th>
      <th>To be completed on</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr>
        <td><%= link_to "#{list.name}", list%> | </td>
        <td><%= list.added_on %> | </td>
        <td><%= list.to_be_completed_on %> | </td>
        <td><%= link_to 'Edit', edit_list_path(list) %> | </td>
        <td><%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List', new_list_path %>
<p>
  <%= link_to 'Back to Homepage', root_path %>
</p>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h2>Name:<strong> <%= link_to @list.name, new_list_item_path(@list.id) %></strong></h2>(Click list name to add a task!)
</p>

<p>
  <strong>List Added on:</strong>
  <%= @list.added_on %>
</p>

<p>
  <strong>List Items:</strong>
  <% @items.each do |item| %>
    <p>
      <%= render item %>
    </p>
  <% end %>
</p>

<p>
  <strong>List to be completed by:</strong>
  <%= @list.to_be_completed_on %>
</p>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>

app/views/welcome/index.html.erb
<h1>Welcome to your personalized To-Do-List</h1><br>
<p>
  <ul>
    <li>
      <h3>View your <%= link_to "Lists", lists_path %> to get started!</h3>
    </li>
  </ul>
</p>